# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import splitlearning_pb2 as splitlearning__pb2


class SplitLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendClientActivations = channel.unary_unary(
                '/splitlearning.SplitLearning/SendClientActivations',
                request_serializer=splitlearning__pb2.ClientToServer.SerializeToString,
                response_deserializer=splitlearning__pb2.ServerToClient.FromString,
                )


class SplitLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendClientActivations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendClientActivations': grpc.unary_unary_rpc_method_handler(
                    servicer.SendClientActivations,
                    request_deserializer=splitlearning__pb2.ClientToServer.FromString,
                    response_serializer=splitlearning__pb2.ServerToClient.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.SplitLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SplitLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendClientActivations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splitlearning.SplitLearning/SendClientActivations',
            splitlearning__pb2.ClientToServer.SerializeToString,
            splitlearning__pb2.ServerToClient.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
