# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import siamese_pb2 as siamese__pb2


class SiameseNetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendVectors = channel.unary_unary(
                '/SiameseNetwork/SendVectors',
                request_serializer=siamese__pb2.VectorRequest.SerializeToString,
                response_deserializer=siamese__pb2.DistanceResponse.FromString,
                )


class SiameseNetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiameseNetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVectors,
                    request_deserializer=siamese__pb2.VectorRequest.FromString,
                    response_serializer=siamese__pb2.DistanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SiameseNetwork', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SiameseNetwork(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SiameseNetwork/SendVectors',
            siamese__pb2.VectorRequest.SerializeToString,
            siamese__pb2.DistanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
