# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: siamese.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsiamese.proto\"\x1b\n\rVectorRequest\x12\n\n\x02v1\x18\x01 \x01(\x05\"2\n\x10\x44istanceResponse\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\x12\x0c\n\x04loss\x18\x02 \x01(\x02\x32\x42\n\x0eSiameseNetwork\x12\x30\n\x0bSendVectors\x12\x0e.VectorRequest\x1a\x11.DistanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'siamese_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORREQUEST']._serialized_start=17
  _globals['_VECTORREQUEST']._serialized_end=44
  _globals['_DISTANCERESPONSE']._serialized_start=46
  _globals['_DISTANCERESPONSE']._serialized_end=96
  _globals['_SIAMESENETWORK']._serialized_start=98
  _globals['_SIAMESENETWORK']._serialized_end=164
# @@protoc_insertion_point(module_scope)
